{{- if .Values.enabled }}
{{- if .Values.scheduler }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    spaceone.service: {{ .Values.name }}
  name: {{ .Values.name }}-scheduler
  namespace: {{ .Values.global.supervisor_namespace | default .Release.Namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      spaceone.service: {{ .Values.name }}-scheduler
  template:
    metadata:
      annotations:
        spaceone.deployment.tool: helm
        spaceone.application-flag: {{ print .Values.application_scheduler | sha256sum }}
      labels:
{{ include "spaceone.labels" . | indent 8 }}
        spaceone.service: {{ .Values.name }}-scheduler
    spec:
{{- if .Values.global.serviceAccountName }}
      serviceAccountName: {{ .Values.global.serviceAccountName }}
{{- end }}
      terminationGracePeriodSeconds: {{ .Values.gracePeriod }}
{{- if .Values.imagePullSecrets}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end}}
      containers:
        - name: kubectl-proxy
          image: {{ .Values.sidecar.kubectl_proxy.image.name }}:{{ .Values.sidecar.kubectl_proxy.image.version }}
{{- if .Values.sidecar.kubectl_proxy.resources }}
          resources:
          {{- toYaml .Values.sidecar.kubectl_proxy.resources | nindent 12 }}
{{- end }}
          ports:
            - containerPort: 8080
{{- if .Values.global.common_env }}
          env:
{{- toYaml .Values.global.common_env | nindent 12 }}
{{- end }}

        - name: redis
          image: {{ .Values.sidecar.redis.image.name }}:{{ .Values.sidecar.redis.image.version }}
{{- if .Values.sidecar.redis.resources }}
          resources:
          {{- toYaml .Values.sidecar.redis.resources | nindent 12 }}
{{- end }}
          ports:
            - containerPort: 6379
{{- if .Values.global.common_env }}
          env:
{{- toYaml .Values.global.common_env | nindent 12 }}
{{- end }}

        - name: {{ .Values.name }}-scheduler
          image: {{ .Values.image.name }}:{{ .Values.image.version }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
{{- if .Values.resources.scheduler }}
          resources:
          {{- toYaml .Values.resources.scheduler | nindent 12 }}
{{- end }}
          command: ['spaceone', 'scheduler', 'spaceone.{{ .Values.name }}']
          volumeMounts:
            - name: default-conf
              mountPath: /opt/spaceone/{{ .Values.name }}/config/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: timezone
              mountPath: /etc/localtime
            - name: log-volume
              mountPath: /var/log/spaceone
            - name: application-conf
              mountPath: /opt/spaceone/{{ .Values.name }}/config/application.yaml
              subPath: application.yaml
              readOnly: true
          env:
            - name: SPACEONE_CONFIG_FILE
              value: /opt/spaceone/{{ .Values.name }}/config/config.yaml
{{- if .Values.global.common_env }}
{{- toYaml .Values.global.common_env | nindent 12 }}
{{- end }}

{{- if .Values.sidecar.scheduler }}
{{- toYaml .Values.sidecar.scheduler | nindent 8 }}
{{- end }}


{{- if .Values.global.supervisor.sidecar }}
{{- toYaml .Values.global.supervisor.sidecar | nindent 8 }}
{{- end }}

      volumes:
        - name: default-conf 
          configMap:
            name: {{ .Values.name }}-conf
        - name: application-conf
          configMap:
            name: {{ .Values.name }}-application-scheduler-conf

{{- if .Values.volumes }}
{{- toYaml .Values.volumes | nindent 8 }}
{{- end }}

{{- if .Values.global.supervisor.volumes }}
{{- toYaml .Values.global.supervisor.volumes | nindent 8 }}
{{- end }}

{{- if .Values.pod.spec }}
{{- toYaml .Values.pod.spec | nindent 6 }}
{{- end }}

{{- end }}
{{- end }}
